version: '3.4'

services:
  otus.teaching.promocodefactory.webhost:
    image: ${DOCKER_REGISTRY-}otusteachingpromocodefactorywebhost
    build:
      context: .
      dockerfile: Otus.Teaching.PromoCodeFactory.WebHost/Dockerfile
    depends_on:
      - dbpgtest
  dbpgtest:
    # We need to do this to get the PostgreSQL container to work on Windows
    container_name: postgres_container_test
    image: postgres
    #build:
    #  context: .
      #dockerfile: AspCoreRazorPostgre/Dockerfile.postgresql-container
    environment:
      PGDATA: '/var/lib/postgresql/data'
      PGUSER: 'postgres'
      USER: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin_container_test
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"

    restart: unless-stopped
volumes:
  pgdata:
    driver: local
  pgadmin: 
